import { useContext, useState, useRef, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { ThemeContext } from '../App'
import { getTheme, getLabelColors, truncate, timeAgo } from '../utils/helpers'

function IssueMenu({ issue, repo, t, theme, onClose, buttonRef, workingOn, onToggleWorking }) {
  const [generating, setGenerating] = useState(false)
  const [copied, setCopied] = useState(false)
  const [pos, setPos] = useState({ top: 0, left: 0 })
  const ref = useRef(null)

  useEffect(() => {
    if (buttonRef.current) {
      const rect = buttonRef.current.getBoundingClientRect()
      const menuHeight = 180
      const showAbove = rect.top > menuHeight
      setPos({
        top: showAbove ? rect.top - menuHeight - 4 : rect.bottom + 4,
        left: rect.right - 240,
      })
    }
    const handler = (e) => {
      if (ref.current && !ref.current.contains(e.target) &&
          buttonRef.current && !buttonRef.current.contains(e.target)) {
        onClose()
      }
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [onClose, buttonRef])

  const generateReport = () => {
    setGenerating(true)
    setTimeout(() => {
      const report = `# Issue Report — PRGuard Codebase Analysis
Generated by PRGuard · ${new Date().toLocaleString()}

---

## Issue #${issue.number}: ${issue.title}

**Labels:** ${issue.labels.join(', ')}
**Opened:** ${timeAgo(issue.created_at)}

---

**Repository:** ${repo}

## Issue Description

${issue.body || 'No issue description was provided.'}

## PRGuard Context

Use the PRGuard chat panel with this issue selected for repository-grounded analysis,
root-cause identification, and a step-by-step fix guide.

---
*Generated by PRGuard — Codebase Learning Assistant*`

      navigator.clipboard.writeText(report).then(() => {
        setCopied(true)
        setGenerating(false)
        setTimeout(() => { setCopied(false); onClose() }, 2000)
      })
    }, 1200)
  }

  const menuItems = [
    { label: 'Generate & Copy Report', icon: '⎘', action: generateReport,          desc: 'Full issue + RAG context + fix guide' },
    { label: 'Copy Issue Link',        icon: '🔗', action: () => { navigator.clipboard.writeText(issue.html_url || `https://github.com/${repo}/issues/${issue.number}`); onClose() }, desc: 'GitHub issue URL' },
    { label: 'Export for ChatGPT',     icon: '↗', action: () => { navigator.clipboard.writeText(`I am working on ${repo} issue #${issue.number}: "${issue.title}".\n\nIssue description:\n${issue.body || 'No description provided.'}\n\nHelp me identify the root cause, relevant files, and a safe implementation plan.`); onClose() }, desc: 'Prompt ready to paste' },
    { label: workingOn ? 'Mark as Not Working On' : 'Mark as Working On', icon: workingOn ? '✓' : '◎', action: onToggleWorking, desc: workingOn ? 'Remove from your work list' : 'Track this issue for yourself' },
  ]

  const menuContent = (
    <div ref={ref} style={{ position: 'fixed', top: `${pos.top}px`, left: `${pos.left}px`, zIndex: 9999, background: t.bg2, border: `1px solid ${t.border}`, borderRadius: 8, padding: '4px 0', width: 240, boxShadow: '0 -4px 24px rgba(0,0,0,0.6)' }}>
      {generating ? (
        <div style={{ padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ display: 'flex', gap: 4 }}>
            {[0, 1, 2].map(i => (
              <div key={i} style={{ width: 6, height: 6, borderRadius: '50%', background: t.accent, animation: 'pulse 1.5s infinite', animationDelay: `${i * 0.15}s` }}/>
            ))}
          </div>
          <span style={{ fontSize: 12, color: t.text2 }}>Generating report...</span>
        </div>
      ) : copied ? (
        <div style={{ padding: '12px 16px' }}>
          <span style={{ fontSize: 12, color: '#22c55e', fontWeight: 500 }}>✓ Copied to clipboard</span>
        </div>
      ) : (
        menuItems.map((item, i) => (
          <div key={i}>
            {i === menuItems.length - 1 && <div style={{ borderTop: `1px solid ${t.border}`, margin: '4px 0' }}/>}
            <button onClick={item.action}
              style={{ width: '100%', textAlign: 'left', padding: '10px 12px', display: 'flex', alignItems: 'flex-start', gap: 10, background: 'transparent', border: 'none', cursor: 'pointer', transition: 'background 0.15s' }}
              onMouseEnter={e => e.currentTarget.style.background = t.bg3}
              onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
              <span style={{ fontSize: 14, color: t.accentText, flexShrink: 0, marginTop: 1 }}>{item.icon}</span>
              <div>
                <div style={{ fontSize: 12, fontWeight: 500, color: t.text }}>{item.label}</div>
                <div style={{ fontSize: 10, color: t.text3, marginTop: 2 }}>{item.desc}</div>
              </div>
            </button>
          </div>
        ))
      )}
    </div>
  )

  return createPortal(menuContent, document.body)
}

export default function IssueList({ issues, selectedIssue, onSelectIssue, loading, repo }) {
  const { theme } = useContext(ThemeContext)
  const t = getTheme(theme)
  const [openMenuId, setOpenMenuId] = useState(null)
  const [workingIssueIds, setWorkingIssueIds] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem('prguard:working-issues') || '[]')
    } catch {
      return []
    }
  })
  const buttonRefs = useRef({})

  const toggleWorking = (issueId) => {
    setWorkingIssueIds(previous => {
      const next = previous.includes(issueId)
        ? previous.filter(id => id !== issueId)
        : [...previous, issueId]
      localStorage.setItem('prguard:working-issues', JSON.stringify(next))
      return next
    })
    setOpenMenuId(null)
  }

  if (loading) return (
    <div style={{ padding: 8 }}>
      {[1, 2, 3].map(i => (
        <div key={i} style={{ height: 80, borderRadius: 6, background: t.bg3, marginBottom: 8, animation: 'pulse 1.5s infinite' }}/>
      ))}
    </div>
  )

  // ── No inner scroll wrapper — parent in Dashboard handles scrolling ──
  return (
    <div>
      {issues.map(issue => {
        const isActive = selectedIssue?.id === issue.id
        const menuOpen = openMenuId === issue.id

        if (!buttonRefs.current[issue.id]) {
          buttonRefs.current[issue.id] = { current: null }
        }

        return (
          <div key={issue.id} style={{ borderLeft: `2px solid ${isActive ? t.accent : 'transparent'}`, background: isActive ? (theme === 'dark' ? '#1a2030' : '#fef3c7') : 'transparent', borderBottom: `1px solid ${t.border}`, position: 'relative', transition: 'all 0.15s' }}>
            <div
              onClick={() => onSelectIssue(issue)}
              style={{ padding: '14px 36px 14px 12px', cursor: 'pointer' }}
              onMouseEnter={e => { if (!isActive) e.currentTarget.parentElement.style.background = t.bg3 }}
              onMouseLeave={e => { if (!isActive) e.currentTarget.parentElement.style.background = 'transparent' }}
            >
              <div style={{ fontSize: 10, color: t.accentText, marginBottom: 6, fontFamily: 'monospace' }}>#{issue.number}</div>
              <div style={{ fontSize: 12, color: t.text2, lineHeight: 1.5, marginBottom: 10 }}>{truncate(issue.title, 44)}</div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
                {issue.labels.map(label => (
                  <span key={label} className={`text-[9px] px-1.5 py-0.5 rounded border ${getLabelColors(theme, label)}`}>{label}</span>
                ))}
                <span style={{ fontSize: 10, color: t.text3, marginLeft: 'auto' }}>{timeAgo(issue.created_at)}</span>
              </div>
            </div>

            <button
              ref={el => buttonRefs.current[issue.id] = { current: el }}
              onClick={(e) => { e.stopPropagation(); setOpenMenuId(menuOpen ? null : issue.id) }}
              style={{ position: 'absolute', top: 14, right: 10, width: 24, height: 24, borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: menuOpen ? t.accentText : t.text3, background: menuOpen ? t.bg3 : 'transparent', border: `1px solid ${menuOpen ? t.border : 'transparent'}`, transition: 'all 0.15s' }}
              title="Issue options">
              <span style={{ fontSize: 13, letterSpacing: 1, lineHeight: 1 }}>···</span>
            </button>

            {menuOpen && (
              <IssueMenu
                issue={issue}
                repo={repo}
                t={t}
                theme={theme}
                onClose={() => setOpenMenuId(null)}
                buttonRef={buttonRefs.current[issue.id]}
                workingOn={workingIssueIds.includes(issue.id)}
                onToggleWorking={() => toggleWorking(issue.id)}
              />
            )}
          </div>
        )
      })}
    </div>
  )
}